### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by AluGeris** [Lemmings19/fallout-2-walkthrough#1]
https://github.com/Lemmings19/fallout-2-walkthrough/blob/cb416db470a3ee99580ca18db1f3b3baf9ebe2bd/index.html#L858
Text in line 858 second sentence "...walk to and fro to..." should be "...walk to and from them to..."

**Comment by Lemmings19** [comment]
"To and fro" is a valid term. The use of "to and fro" here indicates that the player should walk in a zigzag pattern in order to find/spot floor traps.

https://en.wiktionary.org/wiki/to_and_fro
